# -*- coding: utf-8 -*-
"""graph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1glm6lBt8MR6X_i6Hk4fEwBFTTUeLOnMr
"""

import matplotlib.pyplot as plt

# Your exact benchmark data
matrix_sizes = [256, 512, 1024, 2048, 4096, 8192, 16384]

# Times in microseconds
time_naive_us = [176.87, 863.57, 6192.79, 35090.59, 287086.72, 2375388.68, 20494857.22]
time_tiled_us = [231.56, 520.62, 1893.56, 12161.97, 69375.14, 549292.97, 4451290.07]

# Convert microseconds to seconds
time_naive_sec = [t / 1_000_000 for t in time_naive_us]
time_tiled_sec = [t / 1_000_000 for t in time_tiled_us]

# Calculate TFLOPS
tflops_naive = [(2 * (N**3)) / t / 1e12 for N, t in zip(matrix_sizes, time_naive_sec)]
tflops_tiled = [(2 * (N**3)) / t / 1e12 for N, t in zip(matrix_sizes, time_tiled_sec)]

# ----------------- PLOTTING -----------------
plt.style.use('seaborn-v0_8-darkgrid')
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('CUDA Custom 2D Block-Tiled SGEMM vs Naive Kernel (RTX 3050)', fontsize=16, fontweight='bold')

# --- Plot 1: Execution Time (LINEAR Scale) ---
ax1.plot(matrix_sizes, time_naive_sec, marker='o', color='#e74c3c', linewidth=2.5, label='Naive Kernel')
ax1.plot(matrix_sizes, time_tiled_sec, marker='s', color='#2ecc71', linewidth=2.5, label='2D Tiled Kernel')

ax1.set_title('Execution Time (Lower is Better)', fontsize=14, fontweight='bold')
ax1.set_xlabel('Matrix Dimension (N x N)', fontsize=12, fontweight='bold')
ax1.set_ylabel('Time (Seconds)', fontsize=12, fontweight='bold')
ax1.set_xscale('log', base=2) # Keep X-axis log so sizes are spaced evenly
ax1.set_xticks(matrix_sizes)
ax1.set_xticklabels(matrix_sizes)
ax1.legend(fontsize=11)

# Annotate the massive 16K speedup
speedup_16k = time_naive_sec[-1] / time_tiled_sec[-1]
ax1.annotate(f"{speedup_16k:.1f}x Speedup\n(20.5s vs 4.5s)",
             xy=(16384, time_tiled_sec[-1]),
             xytext=(2048, 10), # Adjusted placement for the linear gap
             arrowprops=dict(facecolor='black', shrink=0.05, width=1.5, headwidth=8),
             fontsize=11, fontweight='bold',
             bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="black", lw=1))

# --- Plot 2: TFLOPS (Higher is Better) ---
ax2.plot(matrix_sizes, tflops_naive, marker='o', color='#e74c3c', linewidth=2.5, label='Naive Kernel')
ax2.plot(matrix_sizes, tflops_tiled, marker='s', color='#2ecc71', linewidth=2.5, label='2D Tiled Kernel')

ax2.set_title('Compute Throughput (Higher is Better)', fontsize=14, fontweight='bold')
ax2.set_xlabel('Matrix Dimension (N x N)', fontsize=12, fontweight='bold')
ax2.set_ylabel('Performance (TeraFLOPS)', fontsize=12, fontweight='bold')
ax2.set_xscale('log', base=2)
ax2.set_xticks(matrix_sizes)
ax2.set_xticklabels(matrix_sizes)
ax2.legend(fontsize=11)

# Annotate peak TFLOPS
ax2.annotate(f"Peak: {tflops_tiled[-1]:.2f} TFLOPS",
             xy=(16384, tflops_tiled[-1]),
             xytext=(2048, 1.5),
             arrowprops=dict(facecolor='black', shrink=0.05, width=1.5, headwidth=8),
             fontsize=12, fontweight='bold',
             bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="black", lw=1))

# Final layout adjustments
plt.tight_layout()
plt.subplots_adjust(top=0.88)
plt.savefig('cuda_benchmark_linear.png', dpi=300)
print("Graph saved successfully as 'cuda_benchmark_linear.png'. Ready for LinkedIn!")

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from matplotlib.ticker import FuncFormatter

# Setup Data
matrix_dims = [256, 512, 1024, 2048, 4096, 8192, 16384]
data_us = {
    "Naive":           [401.3, 951.7, 5799.2, 37181.1, 300097.2, 2612513.9, 20918648.3],
    "2D Blocktilling": [339.8, 548.3, 1893.9, 10046.3, 66804.8, 563063.2, 4396641.5],
    "Vectorized":      [327.1, 254.0, 1045.4, 6507.4, 41443.0, 323278.9, 2717967.2],
    "Warptailing":     [270.5, 267.4, 1025.4, 6143.4, 38015.5, 311290.2, 2515279.4]
}
data_s = {label: np.array(times) / 1000000.0 for label, times in data_us.items()}

sns.set_theme(style="darkgrid", context="talk")
colors = ["#e63946", "#f4a261", "#2a9d8f", "#264653"]
markers = ["o", "v", "D", "s"]

# --- PLOT 1: EXECUTION TIME ---
plt.figure(figsize=(12, 8))
for i, (label, times) in enumerate(data_s.items()):
    plt.plot(matrix_dims, times, color=colors[i], marker=markers[i], label=label, linewidth=3, markersize=9)

plt.title('CUDA SGEMM: Execution Time Comparison (RTX 3050)', fontsize=20, fontweight='bold')
plt.xscale('log', base=2)
plt.gca().yaxis.set_major_formatter(FuncFormatter(lambda y, _: '{:g}'.format(y)))

plt.xlabel('Matrix Dimension (N x N)', fontsize=14, fontweight='bold')
plt.ylabel('Time (Seconds)', fontsize=14, fontweight='bold')
plt.xticks(matrix_dims, [str(d) for d in matrix_dims])

# Speedup Annotation
speedup = data_s["Naive"][-1] / data_s["Warptailing"][-1]
plt.annotate(f"{speedup:.1f}x Faster\n(Warp-tailing)",
             xy=(16384, data_s["Warptailing"][-1]), xytext=(4096, 12),
             arrowprops=dict(facecolor='black', shrink=0.05, width=2, headwidth=10),
             fontsize=14, fontweight='bold', bbox=dict(boxstyle="round,pad=0.5", fc="white", ec="black", lw=1.5))

plt.legend()
plt.tight_layout()
plt.show()

# --- PLOT 2: COMPUTE THROUGHPUT ---
def calculate_tflops(n_dims, times_s):
    n = np.array(n_dims)
    return (2 * n**3) / times_s / 1e12

plt.figure(figsize=(12, 8))
for i, (label, times) in enumerate(data_s.items()):
    tflops = calculate_tflops(matrix_dims, times)
    plt.plot(matrix_dims, tflops, color=colors[i], marker=markers[i], label=label, linewidth=3, markersize=9)

plt.title('CUDA SGEMM: Compute Throughput (TFLOPS)', fontsize=20, fontweight='bold')
plt.xscale('log', base=2)
plt.xlabel('Matrix Dimension (N x N)', fontsize=14, fontweight='bold')
plt.ylabel('Performance (TeraFLOPS)', fontsize=14, fontweight='bold')
plt.xticks(matrix_dims, [str(d) for d in matrix_dims])

# Peak Annotation
peak_val = calculate_tflops(matrix_dims, data_s["Warptailing"])[-1]
plt.annotate(f'Peak: {peak_val:.2f} TFLOPS',
             xy=(16384, peak_val), xytext=(4096, 2.5),
             bbox=dict(boxstyle="round,pad=0.5", fc="white", ec="black", lw=1.5),
             arrowprops=dict(facecolor='black', shrink=0.05, width=2, headwidth=10),
             fontsize=14, fontweight='bold', ha='center')

plt.legend()
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Theme and Font Setup
sns.set_theme(style="whitegrid")
plt.rcParams.update({'font.size': 12, 'font.weight': 'bold', 'axes.labelweight': 'bold'})

# Benchmark Data
sizes = [256, 512, 1024, 2048, 4096, 8192, 16384]
x = [str(s) for s in sizes]

naive = [171.50e-6, 972.98e-6, 7040.10e-6, 40604.76e-6, 296082.34e-6, 2444402.00e-6, 22368427.80e-6]
hand_written = [134.04e-6, 350.35e-6, 1018.54e-6, 4419.68e-6, 37114.74e-6, 299730.25e-6, 2663913.65e-6]
cublas_sgemm = [129.67e-6, 163.85e-6, 753.19e-6, 4587.54e-6, 35776.80e-6, 275095.86e-6, 2399587.84e-6]

fig, ax = plt.subplots(figsize=(12, 8))

# Explicit Grid Setup
ax.grid(True, which='both', linestyle='--', linewidth=0.7, color='gray', alpha=0.5, zorder=0)

# Plotting (zorder=3 ensures lines are above the grid)
ax.plot(x, naive, 'r-o', label='Naive Kernel', linewidth=3, markersize=8, zorder=3)
ax.plot(x, hand_written, 's-', color='#ff9f4b', label='Hand-written (Double Buff)', linewidth=3, markersize=8, zorder=3)
ax.plot(x, cublas_sgemm, 'D-', color='#2a9d8f', label='cuBLAS SGEMM', linewidth=3, markersize=8, zorder=3)

# Annotation for Hand-written vs Naive
speedup = naive[-1] / hand_written[-1]
ax.annotate(f'Speedup: {speedup:.1f}x\n(Naive vs Hand-written)',
             xy=(x[-1], hand_written[-1]),
             xytext=(0.65, 0.45), textcoords='axes fraction',
             fontsize=13, fontweight='bold', color='black',
             bbox=dict(boxstyle="round,pad=0.5", fc="white", ec="red", lw=2),
             arrowprops=dict(arrowstyle="->", connectionstyle="arc3,rad=-0.2", color='black', lw=1.5))

# Formatting
ax.set_title("FP32 SGEMM: Execution Time Comparison (RTX 3050)", fontsize=18, pad=20)
ax.set_ylabel("Execution Time (Seconds)", fontsize=14)
ax.set_xlabel("Matrix Dimension (N x N)", fontsize=14)
ax.ticklabel_format(style='plain', axis='y')
ax.legend(frameon=True, shadow=True, facecolor='white', fontsize=12)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Theme and Font Setup
sns.set_theme(style="whitegrid")
plt.rcParams.update({'font.size': 12, 'font.weight': 'bold', 'axes.labelweight': 'bold'})

# Benchmark Data
sizes = [256, 512, 1024, 2048, 4096, 8192, 16384]
x = [str(s) for s in sizes]

naive = [171.50e-6, 972.98e-6, 7040.10e-6, 40604.76e-6, 296082.34e-6, 2444402.00e-6, 22368427.80e-6]
hand_written = [134.04e-6, 350.35e-6, 1018.54e-6, 4419.68e-6, 37114.74e-6, 299730.25e-6, 2663913.65e-6]
cublas_sgemm = [129.67e-6, 163.85e-6, 753.19e-6, 4587.54e-6, 35776.80e-6, 275095.86e-6, 2399587.84e-6]
cublas_hgemm = [70.09e-6, 87.70e-6, 219.56e-6, 1156.75e-6, 6351.98e-6, 49005.49e-6, 530426.26e-6]

fig, ax = plt.subplots(figsize=(12, 8))

# Explicit Grid Setup
ax.grid(True, which='both', linestyle='--', linewidth=0.7, color='gray', alpha=0.5, zorder=0)

# Plotting
ax.plot(x, naive, 'r-o', label='Naive Kernel', linewidth=3, markersize=8, zorder=3)
ax.plot(x, hand_written, 's-', color='#ff9f4b', label='Hand-written (Double Buff)', linewidth=3, markersize=8, zorder=3)
ax.plot(x, cublas_sgemm, 'D-', color='#2a9d8f', label='cuBLAS SGEMM', linewidth=3, markersize=8, zorder=3)
ax.plot(x, cublas_hgemm, 'P-', color='#264653', label='cuBLAS HGEMM (FP16)', linewidth=3, markersize=8, zorder=3)

# Annotation for Hand-written vs Naive
speedup = naive[-1] / hand_written[-1]
ax.annotate(f'Speedup: {speedup:.1f}x\n(Naive vs Hand-written)',
             xy=(x[-1], hand_written[-1]),
             xytext=(0.65, 0.45), textcoords='axes fraction',
             fontsize=13, fontweight='bold', color='black',
             bbox=dict(boxstyle="round,pad=0.5", fc="white", ec="red", lw=2),
             arrowprops=dict(arrowstyle="->", connectionstyle="arc3,rad=-0.2", color='black', lw=1.5))

# Formatting
ax.set_title("GEMM: Execution Time Comparison (All Variants)", fontsize=18, pad=20)
ax.set_ylabel("Execution Time (Seconds)", fontsize=14)
ax.set_xlabel("Matrix Dimension (N x N)", fontsize=14)
ax.ticklabel_format(style='plain', axis='y')
ax.legend(frameon=True, shadow=True, facecolor='white', fontsize=12)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
plt.rcParams.update({'font.weight': 'bold'})

sizes = [256, 512, 1024, 2048, 4096, 8192, 16384]
x = [str(s) for s in sizes]

# Data
naive = [171.50e-6, 972.98e-6, 7040.10e-6, 40604.76e-6, 296082.34e-6, 2444402.00e-6, 22368427.80e-6]
hand_written = [134.04e-6, 350.35e-6, 1018.54e-6, 4419.68e-6, 37114.74e-6, 299730.25e-6, 2663913.65e-6]
hgemm = [70.09e-6, 87.70e-6, 219.56e-6, 1156.75e-6, 6351.98e-6, 49005.49e-6, 530426.26e-6]

plt.figure(figsize=(12, 8))
plt.grid(True, which='both', linestyle='-', linewidth=0.5, color='#d3d3d3')

plt.plot(x, naive, 'r-o', label='Naive Kernel', linewidth=2)
plt.plot(x, hand_written, 's-', color='#ff9f4b', label='Hand-written (FP32)', linewidth=2)
plt.plot(x, hgemm, '^-', color='#264653', label='cuBLAS HGEMM (FP16)', linewidth=4, markersize=10)

# Annotation for HGEMM dominance
plt.annotate(f'HGEMM @ 16k: {hgemm[-1]:.2f}s\n(Tensor Core Advantage)',
             xy=(x[-1], hgemm[-1]),
             xytext=(0.55, 0.15), textcoords='axes fraction',
             fontsize=12, fontweight='bold',
             bbox=dict(boxstyle="round,pad=0.4", fc="#e1f5fe", ec="#264653"),
             arrowprops=dict(arrowstyle="->", color='#264653'))

plt.title("Full GEMM Timeline: Including Tensor Cores", fontsize=18, pad=20)
plt.ylabel("Time (Seconds)")
plt.xlabel("Matrix Dimension (N x N)")
plt.legend(loc='upper left')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Theme and Font Setup
sns.set_theme(style="whitegrid")
plt.rcParams.update({'font.size': 12, 'font.weight': 'bold', 'axes.labelweight': 'bold'})

# Benchmark Data
sizes = np.array([256, 512, 1024, 2048, 4096, 8192, 16384])
x = [str(s) for s in sizes]

naive_s = np.array([171.50e-6, 972.98e-6, 7040.10e-6, 40604.76e-6, 296082.34e-6, 2444402.00e-6, 22368427.80e-6])
hand_written_s = np.array([134.04e-6, 350.35e-6, 1018.54e-6, 4419.68e-6, 37114.74e-6, 299730.25e-6, 2663913.65e-6])
cublas_sgemm_s = np.array([129.67e-6, 163.85e-6, 753.19e-6, 4587.54e-6, 35776.80e-6, 275095.86e-6, 2399587.84e-6])

# Calculate TFLOPS: (2 * N^3) / (time_in_seconds * 10^12)
ops = 2.0 * (sizes ** 3)
naive_tflops = ops / naive_s / 1e12
hand_written_tflops = ops / hand_written_s / 1e12
cublas_sgemm_tflops = ops / cublas_sgemm_s / 1e12

fig, ax = plt.subplots(figsize=(12, 8))

# Explicit Grid Setup
ax.grid(True, which='both', linestyle='--', linewidth=0.7, color='gray', alpha=0.5, zorder=0)

# Plotting
ax.plot(x, naive_tflops, 'r-o', label='Naive Kernel', linewidth=3, markersize=8, zorder=3)
ax.plot(x, hand_written_tflops, 's-', color='#ff9f4b', label='Hand-written (Double Buff)', linewidth=3, markersize=8, zorder=3)
ax.plot(x, cublas_sgemm_tflops, 'D-', color='#2a9d8f', label='cuBLAS SGEMM', linewidth=3, markersize=8, zorder=3)

# Annotation for Hand-written vs Naive TFLOPS at 2048 (Index 3)
idx_2k = 3
speedup = hand_written_tflops[idx_2k] / naive_tflops[idx_2k]
ax.annotate(f'Speedup: {speedup:.1f}x TFLOPS\n(Hand-written vs Naive)',
             xy=(x[idx_2k], hand_written_tflops[idx_2k]),
             xytext=(0.25, 0.65), textcoords='axes fraction',
             fontsize=13, fontweight='bold', color='black',
             bbox=dict(boxstyle="round,pad=0.5", fc="white", ec="red", lw=2),
             arrowprops=dict(arrowstyle="->", connectionstyle="arc3,rad=-0.2", color='black', lw=1.5))

# Formatting
ax.set_title("FP32 SGEMM: Performance Comparison (RTX 3050)", fontsize=18, pad=20)
ax.set_ylabel("Performance (TFLOPS)", fontsize=14)
ax.set_xlabel("Matrix Dimension (N x N)", fontsize=14)
ax.ticklabel_format(style='plain', axis='y')
ax.legend(frameon=True, shadow=True, facecolor='white', fontsize=12)

plt.tight_layout()
plt.show()